services:
  cardvalidation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cardvalidation-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # setting up Kestrel listening on 7135 inside the container
      - ASPNETCORE_URLS=https://+:7135
      # Setting the cert path/password for Dockerfile generating the PFX
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=securepass
    ports:
      - "7135:7135"
    networks: [test-network]

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: cardvalidation-tests
    environment:
      - TEST_API_URL=https://cardvalidation-api:7135
    depends_on: [cardvalidation-api]
    volumes:
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    networks: [test-network]

  report-viewer:
    image: nginx:alpine
    container_name: coverage-report-viewer
    ports:
      - "8080:80"
    volumes:
      - ./coverage/html-report:/usr/share/nginx/html:ro
    networks: [test-network]
    profiles: ["report-viewer"]

networks:
  test-network:
    driver: bridge
